export const WORDS = {
  DEFAULT: [
    "red",
    "blue",
    "green",
    "brown",
    "black",
    "yellow",
    "purple",
    "orange",
    "silver",
    "gold",
    "bronze",
    "cat",
    "dog",
    "cow",
    "rabbit",
    "turtle",
    "pig",
    "horse",
    "whale",
    "shark",
    "fish",
    "bird",
    "bat",
    "lamb",
    "snake",
    "lizard",
    "frog",
    "giraffe",
    "elephant",
    "dinosaur",
    "chicken",
    "penguin",
    "eagle",
    "hawk",
    "aligator",
    "spider",
    "fly",
    "bee",
    "worm",
    "dragon",
    "unicorn",
    "tarantula",
    "steak",
    "pork",
    "beef",
    "milk",
    "honey",
    "sugar",
    "flour",
    "cereal",
    "bread",
    "pasta",
    "pizza",
    "burrito",
    "taco",
    "shrimp",
    "squid",
    "sushi",
    "noodles",
    "china",
    "japan",
    "russia",
    "europe",
    "america",
    "australia",
    "ireland",
    "africa",
    "india",
    "canada",
    "mexico",
    "brazil",
    "superman",
    "batman",
    "spiderman",
    "wonderwoman",
    "hulk",
    "iron man",
    "thor",
    "god",
    "jesus",
    "bible",
    "pray",
    "church",
    "camp",
    "jeep",
    "dirt",
    "water",
    "rain",
    "cloud",
    "sun",
    "star",
    "moon",
    "mars",
    "saturn",
    "comet",
    "asteroid",
    "earth",
    "world",
    "horseshoes",
    "cabin",
    "tent",
    "sleeping bag",
    "stove",
    "oven",
    "fridge",
    "couch",
    "house",
    "chimney",
    "fireplace",
    "car",
    "motorcyle",
    "bus",
    "tank",
    "bike",
    "wagon",
    "scooter",
    "firetruck",
    "police",
    "ambulance",
    "airplane",
    "helicopter",
    "jet",
    "mouse",
    "rat",
    "disneyland",
    "legos",
    "mountain",
    "cliff",
    "sand",
    "beach",
    "wave",
    "starfish",
    "river",
    "lake",
    "volcano",
    "ocean",
    "grass",
    "road",
    "slide",
    "pool",
    "football",
    "soccer",
    "basketball",
    "baseball",
    "wrestling",
    "golf",
    "bowling",
    "darts",
    "cards",
    "poker",
    "blackjack",
    "casino",
    "vegas",
    "new york",
    "san francisco",
    "paris",
    "chicago",
    "miami",
    "detroit",
    "dallas",
    "los angeles",
    "hawaii",
    "california",
    "alaska",
    "texas",
    "florida",
    "colorado",
    "arizona",
    "yosemite",
    "waterfall",
    "mayor",
    "captain",
    "president",
    "chief",
    "indian",
    "cowboy",
    "frankenstein",
    "dracula",
    "halloween",
    "easter",
    "christmas",
    "4th of July",
    "fireworks",
    "mummy",
    "werewolf",
    "clown",
    "circus",
    "puppet",
    "computer",
    "apple",
    "banana",
    "cherry",
    "strawberry",
    "potato",
    "tomato",
    "corn",
    "ketchup",
    "mustard",
    "soda",
    "beer",
    "wine",
    "whiskey",
    "vodka",
    "tequila",
    "kool-aid",
    "trump",
    "clinton",
    "obama",
    "bush",
    "tree",
    "throne",
    "toilet",
    "shower",
    "sword",
    "shield",
    "gun",
    "knife",
    "fork",
    "spoon",
    "jedi",
    "harry potter",
    "darth vader",
    "jail",
    "store",
    "school",
    "college",
    "freeway",
    "airport",
    "work",
    "mickey mouse",
    "donald duck",
    "pokemon",
    "lifegaurd",
    "hospital",
    "taxes",
    "money",
    "coin",
    "wallet",
    "purse",
    "pants",
    "shoes",
    "socks",
    "shirt",
    "jacket",
    "hat",
    "glasses",
    "sunglasses",
    "gloves",
    "jewelry",
    "coffee",
    "starbucks",
    "mcdonalds",
    "latte",
    "rock",
    "glass",
    "iron",
    "wood",
    "cotton",
    "metal",
    "window",
    "door",
    "wall",
    "ceiling",
    "neighbor",
    "cobra",
    "pitbull",
    "bar",
    "towel",
    "soup",
    "soap",
    "math",
    "history",
    "chemistry",
    "lunch",
    "dinner",
    "breakfast",
    "eggs",
    "bacon",
    "pancake",
    "sandwich",
    "peanut butter",
    "snowboard",
    "skateboard",
    "surf",
    "tsunami",
    "earthquake",
    "tornado",
    "hurricane",
    "storm",
    "flood",
    "hollywood",
    "movie",
    "tv",
    "music",
    "band",
    "concert",
    "cartoon",
    "smurf",
    "snoopy",
    "peanut",
    "cracker",
    "chip",
    "facebook",
    "iphone",
    "text",
    "asia",
    "space",
    "astronaut",
    "detective",
    "king",
    "queen",
    "prince",
    "devil",
    "angel",
    "princess",
    "prince",
    "dwarf",
    "soldier",
    "robot",
    "satellite",
    "helmet",
    "goggles",
    "ink",
    "pencil",
    "transformer",
    "toys",
    "baby",
    "child",
    "parent",
    "adult",
    "brother",
    "sister",
    "mom",
    "dad",
    "babysitter",
    "mailman",
    "grass",
    "gas",
    "steam",
    "crane",
    "tractor",
    "truck",
    "palm",
    "hand",
    "foot",
    "stomach",
    "neck",
    "eyes",
    "nose",
    "mouth",
    "ears",
    "head",
    "butt",
    "web",
    "nest",
    "crib",
    "day",
    "night",
    "knight",
    "morning",
    "bottle",
    "plastic",
    "mug",
    "marshmallow",
    "ranger",
    "fire",
    "log",
    "key",
    "fence",
    "rope",
    "garage",
    "thumb",
    "engine",
    "suit",
    "cross",
    "force",
    "theater",
    "ice cream",
    "cookie",
    "cake",
    "mail",
    "light",
    "bell",
    "watch",
    "clock",
    "piano",
    "guitar",
    "stereo",
    "drums",
    "santa",
    "bunny",
    "pumpkin",
    "witch",
    "broom",
    "vacuum",
    "carpet",
    "hoop",
    "hole",
    "ramp",
    "swing",
    "merry go round",
    "park",
    "stick",
    "game",
    "turkey",
    "thanksgiving",
    "vacation",
    "mirror",
    "magic",
    "magician",
    "priest",
    "dance",
    "opera",
    "oprah",
    "ballet",
    "rock n roll",
    "book",
    "novel",
    "comic book",
    "diamond",
    "screen",
    "play",
    "hood",
    "ship",
    "lock",
    "cage",
    "contract",
    "paper",
    "van",
    "nurse",
    "doctor",
    "patient",
    "stock",
    "room",
    "kitchen",
    "yard",
    "chalk",
    "actor",
    "director",
    "wheelchair",
    "medicine",
    "shot",
    "cast",
    "island",
    "country",
    "planet",
    "blanket",
    "suitcase",
    "luggage",
    "bandage",
    "scarf",
    "makeup",
    "cigar",
    "cigarette",
    "drugs",
    "boxing",
    "trunks",
    "camera",
    "telescope",
    "microscope",
    "pie",
    "buffalo",
    "square",
    "triangle",
    "circle",
    "madonna",
    "teddy bear",
    "bear",
    "war",
    "pillow",
    "elvis",
    "michael jordan",
    "beatles",
    "friends",
    "simpsons",
    "JFK",
    "sinatra",
    "kermit",
    "bug bunny",
    "pixar",
    "E.T.",
    "alien",
    "babe ruth",
    "MTV",
    "fox",
    "politics",
    "disease",
    "pickle",
    "spaceship",
    "blimp",
    "portland",
    "hunter",
    "lion",
    "tiger",
    "zebra",
    "safari",
    "france",
    "london",
    "washington",
    "white house",
    "lincoln",
    "puppy",
    "kitten",
    "zoo",
    "aquarium",
    "shelter",
    "forest",
    "oz",
    "galaxy",
    "jupiter",
    "pluto",
    "hose",
    "rope",
    "air conditioner",
    "library",
    "gym",
    "workout",
    "palm",
    "fortune",
    "lottery",
    "picasso",
    "mona lisa",
    "art",
    "museum",
    "skyscraper",
    "subway",
    "beethoven",
    "C3PO",
    "garfield",
    "popeye",
    "flintstone",
    "garden",
    "flower",
    "rose",
    "beast",
    "mermaid",
    "shipwreck",
    "light bulb",
    "DVD",
    "CD",
    "VHS",
    "teacher",
    "student",
    "sports",
    "ring",
    "necklace",
    "skirt",
    "monster",
    "nightmare",
    "dream",
    "imagination",
    "balloon",
    "string",
    "parachute",
    "caveman",
    "army",
    "navy",
    "airforce",
    "marine",
    "thumb",
    "snow",
    "ant",
    "freckle",
    "keys",
    "remote control",
    "GPS",
    "printer",
    "woodstock",
    "tinman",
    "scarecrow",
    "corkscrew",
    "candle",
    "flashlight",
    "match",
    "tokyo",
    "paradise",
    "bermuda",
    "village",
    "poodle",
    "twins",
    "darth vader",
    "yoda",
    "pretzel",
    "investigation",
    "classroom",
    "tie",
    "resume",
    "plate",
    "dishes",
    "bucket",
    "desert",
    "dessert",
    "palm tree",
    "stone",
    "castle",
    "bridge",
    "torch",
    "weapon",
    "underwear",
    "bra",
    "mime",
    "time machine",
    "crystal ball",
    "jetpack",
    "prisoner",
    "leader",
    "sunglasses",
    "microphone",
    "bolt",
    "lightning",
    "thunder",
    "street",
    "mailbox",
    "wheel",
    "chain",
    "seat",
    "seattle",
    "pacific",
    "phoenix",
    "milk",
    "lemonade",
    "juice",
    "tiger woods",
    "muhammad ali",
    "joker",
    "wig",
    "adam sandler",
    "will ferrell",
    "keyboard",
    "zombie",
    "fairy",
    "rainbow",
    "leprechaun",
    "valentine",
    "heart",
    "brain",
    "stomach",
    "kidney",
    "tongue",
    "skeleton",
    "elf",
    "hobbit",
    "giant",
    "beans",
    "willy wonka",
    "oompa loompa",
    "milky way",
    "scuba diver",
    "atlantis",
    "egypt",
    "rome",
    "italy",
  ],
  BARATTA: [
    "Baccala",
    "San Juan Way",
    "Lake Almanor",
    "Lake Tahoe",
    "Fadu",
    "Muckey Trolley",
    "Gorgeous Gorgeous",
    "San Luis Obispo",
    "UOP",
    "Medicine Shoppe",
    "Wobble",
    "Kazoos",
    "cheese",
    "Beretta",
    "Tony",
    "Pat",
    "Mary Kay",
    "Mike",
    "Joseph",
    "Jofus",
    "Patty",
    "Charlie",
    "Sue",
    "Dave",
    "Lynette",
    "Cave Creek",
    "Pleasanton",
    "Air Traffic Control",
    "Doctor",
    "Pharmacist",
    "Sinbad",
    "Bailey",
    "Janelle",
    "Jeff",
    "Klein",
    "Anthony",
    "Max",
    "Danny",
    "John",
    "Emma",
    "Macy",
    "Matthew",
    "Emily",
    "Sarah",
    "Jordan",
    "Andy",
    "Kylie",
    "Julia",
    "Tyler",
    "Waneka",
    "Buster",
    "Josh",
    "Jill",
    "Jessie",
    "Kurt",
    "Lemon tree",
    "Ice house",
    "Dubai",
    "Ukiah",
    "Maui",
    "Marriott",
    "U of A",
    "UC Davis",
    "Loma Linda",
    "Washington D.C.",
    "Arlington",
    "Duke",
    "Hot Lips",
    "Lucy",
    "Charlie Tuna",
    "Auntie Patio",
    "Sar Sar",
    "Knuckle Head",
    "Shua",
    "Danny Boy",
    "Bop",
    "Cheese Bread",
    "ItsIts",
    "Flutterbys",
    "thumbless",
    "BBQ Chicken",
    "Knuckles ",
    "Treehouse",
    "Figueroa Drive",
    "Antipasto",
    "Grays",
    "Millars",
    "Fowlers",
    "Slug bug",
    "St. Augustine's",
    "Cinnamon Rolls",
    "Swimming",
    "Prison ministry",
    "Carpet Yarns",
    "Corral Burgers",
    "Graveyard",
    "Bird Farm",
    "Moon shoes",
    "nail",
    "Aligator bath",
    "Amador Liquors",
    "Pat Cates",
    "Cardboard surfing",
    "Bergeron",
    "Formica counter",
    "Substitute teacher",
    "Raiders",
    "Patty and Peggy",
    "Alameda County Fair",
    "Fireworks",
    "parade",
    "Kybird",
    "Birdie Girl",
    "Susie Q",
    "Jilldebeast",
    "Where's Andrew?",
    "D.C. elevator",
    "Firefighters",
    "Todd",
    "Julia-Kabulia",
    "St. Felicitas",
    "band-aid",
    "Broken arm",
    "Trix",
    "Goldfish",
    "fire hydrant",
    "slo-mo jump",
    "Patio",
    "strawberries",
    "zucchinini",
    "Tony's garden",
    "Apricot tree",
    "Bee hive",
    "Jubilee",
    "Cruise",
    "Snorkeling",
    "Kurt?!",
    "Homemade pizza",
    "Zucchini bread",
    "Pork chops",
    "Horse",
    "Pool",
    "San Leandro",
    "Rumpus room",
    "Banglois",
    "Roybals",
    "Mexican Train",
    "Ace Ventura",
    "Corn Nuts",
    "Pistachios",
    "BBQ Chips",
    "Mr. Goodbar",
    "Pickled Pig's feet ",
    "Salami",
    "Linguica",
    "The ruler!!",
    "Granfather clocks",
    "music boxes",
    "Kylie's motorcycle",
    "Israel",
    "Ireland",
    "Italy",
    "Dryer sheets",
    "Pitbull ",
    "Pitbulls ",
    "Family Feud",
    "Amador High School",
    "tree fort",
    "Stai 'zitto e mangi",
    "fence boards",
    "Army",
    "Hope Hospice",
    "raise the roof",
    "Keith",
    "Vail",
    "Colorado",
    "Arizona",
    "Ice skating",
    "Phoenix",
    "P-town",
    "Pleasanton",
    "Placerville",
    "man",
    "star",
    "road",
    "bubble",
    "level",
    "things",
    "eggnog",
    "frog",
    "company",
    "connection",
    "box",
    "rings",
    "battle",
    "stocking",
    "cow",
    "force",
    "chicken",
    "language",
    "beginner",
    "view",
    "seashore",
    "earth",
    "advertisement",
    "voyage",
    "health",
    "growth",
    "screw",
    "fly",
    "fall",
    "tail",
    "day",
    "quill",
    "teaching",
    "power",
    "lumber",
    "flower",
    "pleasure",
    "loaf",
    "babies",
    "trousers",
    "watch",
    "glass",
    "mice",
    "weight",
    "hobbies",
    "camera",
    "salt",
    "verse",
    "tramp",
    "number",
    "pancake",
    "meat",
    "turn",
    "house",
    "minister",
    "name",
    "plastic",
    "jar",
    "belief",
    "top",
    "fish",
    "driving",
    "cactus",
    "boot",
    "twist",
    "birds",
    "chance",
    "desk",
    "vacation",
    "temper",
    "girls",
    "system",
    "hair",
    "flag",
    "shape",
    "girl",
    "bikes",
    "line",
    "wound",
    "snow",
    "hook",
    "spark",
    "end",
    "match",
    "limit",
    "regret",
    "discussion",
    "cart",
    "volcano",
    "dust",
    "camp",
    "group",
    "jail",
    "knot",
    "measure",
    "crib",
    "smile",
    "title",
    "peace",
    "substance",
    "hors d'ouvres",
    "Steve Martin",
    "Turd Ferguson ",
    "Cattywampus",
    "P!nk",
    "James Caviezel",
    "Courteney Cox",
    "Jason Biggs",
    "Bob Marley",
    "Nicole Kidman",
    "Brad Pitt",
    "Stacey Dash",
    "Justin Theroux",
    "Catherine Zeta-Jones",
    "Eminem",
    "Daniel Radcliffe",
    "Paul Rudd",
    "William Shatner",
    "Howard Stern",
    "Jay Leno",
    "Will Ferrell",
    "Dwayne Wade",
    "Jaden Smith",
    "Ryan Seacrest",
    "Justin Timberlake",
    "Sarah Jessica Parker",
    "Vince Vaughn",
    "Zooey Deschanel",
    "Denzel Washington",
    "Ashley Judd",
    "Jessica Biel",
    "Keira Knightley",
    "Bob Hope",
    "Morgan Freeman",
    "Kenny Chesney",
    "Johnny Depp",
    "Ray Romano",
    "Victoria Beckham",
    "Mila Kunis",
    "Warriors",
    "New York, New York",
    "Texas",
    "Cleveland",
    "Cavs",
    "Anaheim",
    "Florida",
    "Oakland",
    "Minneapolis",
    "San Francisco",
    "Arlington",
    "San Diego",
    "San Jose",
    "Seattle",
    "Sacramento",
    "Portland",
    "Stockton",
    "Las Vegas",
    "Atlanta",
    "Pennsylvania",
    "Louisiana",
    "Boston",
    "New Orleans",
    "Miami",
    "toothpaste",
    "lip gloss",
    "blanket",
    "conditioner",
    "keyboard",
    "cup",
    "phone",
    "photo album",
    "balloon",
    "flag",
    "purse",
    "newspaper",
    "perfume",
    "chalk",
    "CD",
    "zipper",
    "coasters",
    "sandal",
    "magnet",
    "fork",
    "sponge",
    "computer",
    "bracelet",
    "helmet",
    "tomato",
    "eraser",
    "vase",
    "flowers",
    "stockings",
    "apple",
    "brocolli",
    "sofa",
    "speakers",
    "rusty nail",
    "money",
    "carrots",
    "outlet",
    "chair",
    "door",
    "puddle",
    "glasses",
    "sand paper",
    "soda can",
    "thermometer",
    "rug",
    "needle",
    "lamp",
    "cork",
    "mouse pad",
    "beef",
    "blouse",
    "towel",
    "sidewalk",
    "watch",
    "checkbook",
    "bowl",
    "headphones",
    "television",
    "bread",
    "grid paper",
    "socks",
    "thread",
    "bookmark",
    "eye liner",
    "wallet",
    "toothbrush",
    "canvas",
    "pillow",
    "plate",
    "water bottle",
    "wagon",
    "monitor",
    "lace",
    "window",
    "key chain",
    "piano",
    "paper",
    "shawl",
    "radishes",
    "rabbits",
    "horseradish",
    "honey",
    "almonds",
    "turtle",
    "cinnamon",
    "sushi",
    "oranges",
    "cactus",
    "onions",
    "almond butter",
    "pancetta",
    "provolone",
    "feta",
    "sour cream",
    "grits",
    "mackerel",
    "peas",
    "applesauce",
    "pinto beans",
    "hot sauce",
    "curry powder",
    "dill",
    "duck",
    "maple syrup",
    "cashew nut",
    "snapper",
    "olives",
    "avocados",
    "portabella mushrooms",
    "bacon grease",
    "graham crackers",
    "shitakes",
    "hamburger",
    "shallots",
    "aioli",
    "sugar",
    "dried leeks",
    "ale",
    "curry paste",
    "granola",
    "pea beans",
    "succotash",
    "papayas",
    "chicken liver",
    "oregano",
    "anchovies",
    "bok choy",
  ],
};